site_name: PEUE

theme:
  name: material
  palette:
    primary: deep-purple
  font:
    text: Roboto
    code: Roboto Mono
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - search.suggest
    - search.highlight
    - search.share

  logo: https://cdn.worldvectorlogo.com/logos/eu.svg
  favicon: https://european-union.europa.eu/profiles/contrib/ewcms/themes/ewcms_theme/favicon.ico

copyright: MIT

nav:
  - PEUE: index.md
  - Tema 1: tema-1.md
  - Tema 2: tema-2.md
  - Tema 3: tema-3.md
  - Tema 4: tema-4.md
  - Tema 5: tema-5.md
  - Tema 6: tema-6.md
  - Tema 7: tema-7.md
  - Tema 8: tema-8.md
  - Tema 9: tema-9.md
  - Tema 10: tema-10.md

repo_name: team-ittade/peue
repo_url: https://github.com/team-ittade/peue

extra_css:
  - css/colors.css
  - css/custom.css
  - css/pied-piper.css

extra_javascript:
  - js/links.js
  - js/mathjax.js
  - js/progress.js
  - js/readtime.js
  - js/tablesort.js
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://unpkg.com/mermaid@8.4.6/dist/mermaid.min.js


markdown_extensions:
  - admonition
  - attr_list
  - codehilite
  - def_list
  - extra
  - footnotes
  - md_in_html
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tilde
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown_include.include:
      base_path: content
  - pymdownx.tasklist:
      custom_checkbox: true
  - toc:
      permalink: 🔗

plugins:
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
      enable_creation_date: true
  - search
