name: github pages

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - name: Check out repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Provision python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Install python modules
        run: pip install --upgrade mkdocs-material markdown-include mkdocs-git-revision-date-localized-plugin
      - name: Build and deploy web to github pages
        run: mkdocs gh-deploy --force
